version: "3.7"

services:
  labelDb:
    image: mongo:4.4
    command: mongod --port 55431
    volumes:
      - mongo-storage:/data/db
    expose:
      - 55431
    ports:
      - 55431:55431
  backend:
    build:
      context: ./
      dockerfile: DockerfileLocal
    environment:
      - RUN_MODE=LOCAL
    #    image: label-image
    ports:
      - 55430:55430
      - 55433:55432
    depends_on:
      - labelDb

networks:
  default:
    name: label-network

volumes:
  mongo-storage:
    driver: local
    name: label-mongo-storage
