---
- name: Creation secret label backend
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ label_back_app_id }}-secret"
        namespace: "{{ label_kube_namespace }}"
        labels:
          app: "{{ label_back_app_id }}"
      type: Opaque
      data:
        LABEL_DB_URL: "{{ label_mongodb_url | b64encode }}"
        DBSDER_API_KEY: "{{ dbsder_api_key | b64encode}}"
        COOKIE_PRIVATE_KEY: "{{ cookie_private_key | b64encode}}"
