name: Daily merge (master to pre-prod)

on:
  workflow_dispatch:
  schedule:
    - cron: "00 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: git config --local user.email "actions@github.com"
      - run: git config --local user.name "GitHub Actions"
      - run: git checkout master
      - run: git pull
      - run: git checkout pre-prod
      - run: git pull
      - run: git reset origin/master
      - run: git push --force
